language: python
cache: pip
python:
  - 2.7
  - 3.5
# command to install dependencies
install:
  - make dev install
# command to run tests
script:
  - make travis
after_success:
  coveralls --rcfile=.coveragerc
