language: python
cache: pip
python:
  - 2.7
  - 3.5
install:
  - make dev install
script:
  - nosetests -w pub2 -c etc/tests-travis.cfg --with-coverage --cover-package=pub2
after_success:
  - coveralls --rcfile=.coveragerc
